#!/bin/sh

change_mode dracula &
dwmblocks &
xset r rate 300 50 &
sxhkd &
conky &
conky -q -c ~/.config/conky/conky2.conf &

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	pidof -s ! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
