#!/bin/sh

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	nvim="NVIM_LISTEN_ADDRESS="/tmp/nvimsocket-"$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)"" nvim" \
	ssh="ssh -F $SSH_CONFIG -i $SSH_ID -o UserKnownHostsFile=$SSH_KNOWN_HOSTS" \
	ssh-copy-id="ssh-copy-id -i $SSH_ID -o UserKnownHostsFile=$SSH_KNOWN_HOSTS" \
	scp="scp -F $SSH_CONFIG -i $SSH_ID -o UserKnownHostsFile=$SSH_KNOWN_HOSTS" \
	wget="wget --hsts-file $XDG_DATA_HOME/wget/wget-hsts" \
	steam="steamxdg" \
