#!/bin/sh

READ_FROM_PRIMARY=0 # if false it will read from clipboard

PRONOUNCIATION=1

TRANSLATION=1

DICT=1

TARGET=en # language

PRONOUNCIATION_CHOICES=(
	"Default:searx.ekmekci.me/search?q=%s"
	"English:forvo.com/search/%s/"
    "Deutsch:forvo.com/search/%s/"
)

DICT_CHOICES=(
	"Default:searx.ekmekci.me/search?q=%s"
	"English:dictionary.cambridge.org/dictionary/english/%s"
    "Deutsch:dictionary.cambridge.org/dictionary/german-english/%s"
)
